repository: Grace-Engine-Org/GraceEngine

title: Grace Engine Docs
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from

favicon_ico: "/assets/images/GraceEngineLogoMini.ico"
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "See GraceEngine on Github":
    - "//github.com/Grace-Engine-Org/GraceEngine"

# Makes Aux links open in a new tab.
aux_links_new_tab: true
color_scheme: dark

# Disable toc
show_table_of_contents: false

#Set colour of callouts
callouts:
  important:
    title: Important
    color: purple
  note:
    title: Note
    color: blue