name: GraceEngine Build

on:
  pull_request:
    branches: [ "stable" ]
    types: [labeled, synchronize, opened, reopened, edited]

jobs:
  run-if-labeled:
    if: contains(github.event.pull_request.labels.*.name, 'Github Action')
    uses: Grace-Engine-Org/GraceEngine/.github/workflows/Build.yml@stable
    with:
      pr-number: ${{ github.event.pull_request.number }}
    permissions:
      contents: read
      pull-requests: read
